### ISSUE TITLE
Feature Request: Please make the Privoxy Port Configurable

### ISSUE THREAD

**Issue by mathos** [binhex/arch-sabnzbdvpn#1]
I'm not sure with the ip table rule rework if it will take nicely to just switching the external port (i.e. "-p 8119:8118") .  (Actually, if I may also sneak an additional feature request about some more details on privoxy and/or a "tl;dr" would have been very helpful.)  I was going to activate it for that container but have a conflict.  A quick look suggests it is just a quick fix in the iptable.sh script.

**Comment by binhex** [comment]
You can specify whatever port you want on the host side for privoxy and it will just work.
