### ISSUE TITLE
Why no nzbgetvpn version?

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-sabnzbdvpn#11]
I was about to point someone at your client + vpn images, but... there isn't an nzbgetvpn! :)

**Comment by binhex** [comment]
cos i am only one person supporting dozens of docker images perhaps :-) and secondly nzbget is currently broken for arch base, unpack bug (linked below) and until that is resolved there isnt really any point, no idea currently how to fix it.

https://github.com/nzbget/nzbget/issues/558

**Comment by fryfrog** [comment]
Ah, dang.

I know it doesn't really help, but I ran nzbget native on Arch for ages and never saw this issue. Hopefully it gets magically fixed in v21. :(
