### ISSUE TITLE
/tmp/checkdns and /temp/checkiptables has no read permissions

### ISSUE THREAD

**Issue by Caedis** [binhex/arch-sabnzbdvpn#12]
Host: Unraid

Workaround: `chmod +r /tmp/check*`

Log Error:
![image](https://user-images.githubusercontent.com/18713839/61602312-9e74ac00-abfe-11e9-90c9-b21efd5c4f01.png)

Permissions (or lack of) of the files:
![image](https://user-images.githubusercontent.com/18713839/61602191-3920bb00-abfe-11e9-9127-64f4ffe539cd.png)

**Comment by binhex** [comment]
i would suspect you have UMASK set too restrictively, as chmod for both of those files is already performed.

**Comment by Caedis** [comment]
Where would I set that for a container?

**Comment by binhex** [comment]
You would set it via 'umask' env var as part of the docker run command

**Comment by Caedis** [comment]
ahh, for some reason, the unraid docker template (from CommunityApps) had it as UMASK when it should have been lowercase. Fixed when I made that change. Thank you

**Comment by binhex** [comment]
No that's not the cause, it is supposed to be upper case
