### ISSUE TITLE
Fails to build with /var/cache/pacman/pkg/patch-2.7.6-7-x86_64.pkg.tar.xz is corrupted

### ISSUE THREAD

**Issue by martinbaines** [binhex/arch-sabnzbdvpn#14]
When attempting to build the following errors occur:

.... (many package downloads) .... then:
**checking keyring...
checking package integrity...
:: File /var/cache/pacman/pkg/patch-2.7.6-7-x86_64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] error: patch: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
error: failed to commit transaction (invalid or corrupted package)

Errors occurred, no packages were upgraded.
The command '/bin/sh -c chmod +x /root/*.sh /home/nobody/*.sh &&        /bin/bash /root/install.sh' returned a non-zero code: 1**
-----
Details from docker version:
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.12
  GitCommit:        35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by binhex** [comment]
just done a build and it went through fine, of note is the patch package has had a bump in version, so perhaps this fixed the signature issue, please try a build again.

**Comment by martinbaines** [comment]
Great. Yes just tried another build and it worked fine,
Thanks.
