### ISSUE TITLE
Cannot build container (or any other vpn based container)

### ISSUE THREAD

**Issue by jshridha** [binhex/arch-sabnzbdvpn#22]
When trying to build this container, I get the following error message. I suspect that something is wrong in the pacman repositories, but I don't know how to fix it.  The error occurs in the upd.sh script at the `pacman` call after the `pacman -Syyu` call

Sorry I couldn't find the correct repository that has that script, so I'm posting this issue here. Any help would be great. I'm trying to update my nzbget container to use your updated base image with wireguard.

```
( 6/11) Creating temporary files...
( 7/11) Reloading device manager configuration...
  Skipped: Device manager is not running.
( 8/11) Arming ConditionNeedsUpdate...
( 9/11) Reloading system bus configuration...
  Skipped: Current root is not booted.
(10/11) Warn about old perl modules
(11/11) Updating the info directory file...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   160    0   160    0     0    415      0 --:--:-- --:--:-- --:--:--   415
100 2425k  100 2425k    0     0  3141k      0 --:--:-- --:--:-- --:--:-- 17.7M
error: failed to initialise alpm library
(could not find or read directory: /var/lib/pacman/)
The command '/bin/sh -c chmod +x /root/*.sh /home/nobody/*.sh &&        /bin/bash /root/install.sh' returned a non-zero code: 255
```

**Comment by binhex** [comment]
yep i just got hit with this, its a arch linux issue:- https://bugs.archlinux.org/task/69563

apparently its related to glibc

**Comment by binhex** [comment]
im going to rebuild the base, apparently glibc 2.33-4 SHOULD fix this.

**Comment by jshridha** [comment]
Sounds good. I'm happy to test it out after the build is complete.

**Comment by martinbaines** [comment]
How is this going? I just pulled a version and it still did not build with the usual message:

Sending build context to Docker daemon  287.2kB
Step 1/11 : FROM binhex/arch-int-vpn:latest
 ---> 113f717e33a9
Step 2/11 : MAINTAINER binhex
 ---> Running in 753c0d6870cc
Removing intermediate container 753c0d6870cc
 ---> 7e17f29e43cd
Step 3/11 : ADD build/*.conf /etc/supervisor/conf.d/
 ---> 52203ac1e006
Step 4/11 : ADD build/root/*.sh /root/
 ---> f177e2b70d42
Step 5/11 : ADD run/nobody/*.sh /home/nobody/
 ---> 1640b3a0767e
Step 6/11 : RUN chmod +x /root/*.sh /home/nobody/*.sh &&        /bin/bash /root/install.sh
 ---> Running in ff134601f71c
[info] OS_ARCH defined as 'x86-64'
error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)

**Comment by binhex** [comment]
in order to now build with the latest base you need to be running the latest version of 'runc', im not too sure what platform you guys are trying to use to build the image, but whatever it is you will now need this installing on the host doing the build of the image:- https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc93

see the assets and download the static binary, then replace existing runc with this one and you will then be able to build again, obviously in time latest runc will get include with the next docker release, but until that time this is required.

**Comment by jshridha** [comment]
Do you happen to know if docker hub has the latest runc? That fixed things on my local machine but all my builds occur on docker hub.

**Comment by binhex** [comment]
> Do you happen to know if docker hub has the latest runc? That fixed things on my local machine but all my builds occur on docker hub.

nope, you cant currently build on docker hub, it just so happens that i luckily moved over to github actions, which is a much more flexible platform akin to GitLab, so you can install whatever version of runc you want on the runner.

**Comment by jshridha** [comment]
I see your build scripts, so I can start with those to help with the migration. Thanks for the help.
