### ISSUE TITLE
Docker gives 'kernel too old' message

### ISSUE THREAD

**Issue by dvandonkelaar** [binhex/arch-sabnzbdvpn#25]
After using the latest docker (digest 404e30ad728e), docker logs gives the following error:
`FATAL: kernel too old`

Maybe this is not an [arch-sabnzbdvpn](https://github.com/binhex/arch-sabnzbdvpn)-issue but rather an [arch-int-vpn](https://github.com/binhex/arch-int-vpn)-issue or an [arch-base](https://github.com/binhex/arch-base)-issue (I saw those linked in the dockerfiles).

**Comment by binhex** [comment]
duplicate:- https://github.com/binhex/arch-delugevpn/issues/256#issuecomment-787561845
