### ISSUE TITLE
sabnzbd 3.4.0 missing py package dependancy 'guessit'  

### ISSUE THREAD

**Issue by benjithompson** [binhex/arch-sabnzbdvpn#26]
**Issue**

After sabnzbd update, container failed to start with error:  <module> not found 'guessit'

From Sabnzbd 3.4.0 changelog:

> -  Added additional pattern keys that can be used in the Sort String for Sorting, by using the guessit package internally for parsing.

Workaround was to install the package manually.

**Expected**

Container should include the newly required package.

**Comment by binhex** [comment]
This had been fixed upstream, please pull latest image
