### ISSUE TITLE
3.6.1 latest build seems to break Privoxy

### ISSUE THREAD

**Issue by nickp27** [binhex/arch-sabnzbdvpn#30]
My docker build  on Unraid auto-updated to the latest build overnight. I noticed 12 hours later than anything relying on privoxy hadn't been connecting to the internet. The only thing in the logs I could spot was the docker saying that privoxy was not running. Rolling back to 3.6.0-2-01 appears to have fixed the problem.

**Comment by V1P-J0K3R** [comment]
Hi i have the same problem. After Update Radarr, Sonarr and Lidarr can not Talk anymore with sabnzbd and i can not use this container as a proxy anymore.

**Comment by dsfsdbvxc** [comment]
Yup, same probelm here. Yea, rolling back to 3.6.0-2-01 worked

**Comment by vswitch** [comment]
This is resolved now in the latest release:
https://github.com/binhex/arch-sabnzbdvpn/releases/tag/3.6.1-1-03

**Comment by rgpollitt** [comment]
Same problem here

**Comment by vswitch** [comment]
This is resolved in 3.6.1-1:
https://github.com/binhex/arch-sabnzbdvpn/releases/tag/3.6.1-1-03

**Comment by binhex** [comment]
It's fixed pull-down latest and you should be good

**Comment by rgpollitt** [comment]
Indeed working again with 3.6.1-1-03. Thanks!!
