### ISSUE TITLE
Error on startup after update

### ISSUE THREAD

**Issue by lwolfs** [binhex/arch-sabnzbdvpn#32]
Hi,\
I am running arch-sabnzbdvpn in a docker container on Ubuntu. Just upgraded to version 3.7.1 [479daf0] of sabnzbd,
Python 3.10.8 (main, Nov 1 2022, 14:18:21) [GCC 12.2.0] [UTF-8] and OpenSSL 3.0.7 1 Nov 2022.

On startup I see the following error in de webgui.

>  [19/Dec/2022:11:20:48] ENGINE Error in HTTPServer.serve
>Traceback (most recent call last):
> File "/usr/lib/sabnzbd/venv/lib/python3.10/site-packages/cheroot/server.py", line 1807, in serve
>    self._connections.run(self.expiration_interval)
> File "/usr/lib/sabnzbd/venv/lib/python3.10/site-packages/cheroot/connections.py", line 198, in run
>    self._run(expiration_interval)
>  File "/usr/lib/sabnzbd/venv/lib/python3.10/site-packages/cheroot/connections.py", line 241, in _run
>    new_conn = self._from_server_socket(self.server.socket)
>  File "/usr/lib/sabnzbd/venv/lib/python3.10/site-packages/cheroot/connections.py", line 295, in _from_server_socket
>    s, ssl_env = self.server.ssl_adapter.wrap(s)
>  File "/usr/lib/sabnzbd/venv/lib/python3.10/site-packages/cheroot/ssl/builtin.py", line 270, in wrap
>    s = self.context.wrap_socket(
>  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
>    return self.sslsocket_class._create(
>  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
>    self.do_handshake()
>  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
>    self._sslobj.do_handshake()
>ssl.SSLZeroReturnError: TLS/SSL connection has been closed (EOF) (_ssl.c:997)`3.7.1 [[479daf0](https://github.com/sabnzbd/sabnzbd/commit/479daf0)]

**Comment by binhex** [comment]
https://forums.unraid.net/topic/44118-support-binhex-sabnzbd/?do=findComment&comment=1204114

**Comment by binhex** [comment]
Worked around in latest image, please pull down, closing
