### ISSUE TITLE
Par2Cmdline-turbo not showing up as installed on AMD64 system

### ISSUE THREAD

**Issue by IrishTR** [binhex/arch-sabnzbdvpn#38]
Par2cmdline-turbo:	Not available Speed up repairs by installing par2cmdline-turbo, it is available for many platforms.

This alert appears from standard usage on a regular amd64 Docker Host.  I was looking thru the code and see the call out about arm64 not supporting Par2cmdline-turbo, but this is a non-arm system acting like its not installed.

Usage of regular sabnbzd image from linuxserver/sabnzbd (without the VPN) shows it installed on the same setup.  Hope this is enough info please let me know if you need anything else.

**Comment by binhex** [comment]
Yes the inclusion of par2cmdline-turbo is there but i had not built the image (test only), i have now kicked off a build which will include it, please pull down the latest image in around 30 mins from this post time.

**Comment by IrishTR** [comment]
> Yes the inclusion of par2cmdline-turbo is there but i had not built the image (test only), i have now kicked off a build which will include it, please pull down the latest image in around 30 mins from this post time.

Awesome thanks for the update!
