### ISSUE TITLE
DNS lookups broken

### ISSUE THREAD

**Issue by Nativedude** [binhex/arch-sabnzbdvpn#5]
Good afternoon
I've found that builds post this one, dns lookups to my internal network DNS are not working
https://github.com/binhex/arch-sabnzbdvpn/commit/fa9910dd8729464179dff9c79daf8e3b0d501c43

Adding the two firewall rules that you removed in this commit does indeed get them working again
This is true for both the sabnzbd and the deluge dockers

**Comment by binhex** [comment]
dns lookups to my internal network DNS are not working

This is correct, to prevent ip leakage via dns lookup over your lan, all dns queries are now blocked whilst the vpn is running forcing all ns queries to go over the vpn tunnel, what exactly is your issue with this being in place?.

**Comment by Nativedude** [comment]
Gotcha
I was using my internal dns server before so that explains why it stopped
working
Should be good if I switch it to just use google dns or something

**Comment by binhex** [comment]
yes, i would advise using opendns, or if your with pia you can use their name servers, but to be honest it doesnt matter too much, as you cannot be tracked back now due to all queries having your vpn ip address only and not your isp's ip address (default would be good enough).
