### ISSUE TITLE
Synology - Local Time

### ISSUE THREAD

**Issue by MilkmanCDN** [binhex/arch-sabnzbdvpn#8]
When loading configuring the Volume mounts, there's a requirement of:

-v /etc/localtime:/etc/localtime:ro \

Unfortunately the Synology docker GUI doesn't let you add system level directories (has to be under /volume1).   

If this is a method to set the timezone, I believe the more common thing is:

-e TZ=America/Toronto \

A list of time-zone database codes can be found here:

https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

**Comment by binhex** [comment]
ok good info for synology users, closing as you seemed to of worked this out yourself.
